doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: 'mariadb-10.3.25'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_520_ci
        url: '%env(resolve:DATABASE_URL)%'
