#!/usr/bin/env bash
# Deploy script

# get latest tag
latestTag="$(git describe --abbrev=0 --tags)";

function askTag {
    echo "Deploy tag: [$latestTag]"

    ok=0;
    while [ "$ok" = "0" ] ; do
        read userinput

        tagExists=$(git show-ref | grep -c "$userinput")

        if [ "$userinput" = "" ]
        then
            ok=1;
            tag="$latestTag"
        elif [ "$tagExists" = "0" ]
        then
            echo "Invalid tag"
            echo "$tagExists"
        else
            ok=1;
            tag="$userinput"
        fi
    done
}

# gathering information
askTag

printf -v limit "webserver_production"

echo -e "Limit: $limit"

#complete
echo -e "Deploy to webserver(s) with \e[32m\e[1m\e[4mproduction\e[0m environment(s) with tag \e[32m\e[1m\e[4m$tag\e[0m:"
ansible-playbook ansible/deploy/deploy.yml --extra-vars "project_version=$tag" --limit=$limit --ask-vault-pass
